@startuml

title Usecase for Lab7

left to right direction

actor Користувач
actor Споживач


recatangle Software {

  usecase (Авторизувати користувача)
  usecase (Отримати інформацію із рекамендацією про навколишнє середовище)

  :Користувач: -- (Авторизувати користувача)
  :Споживач: -- (Отримати інформацію із рекамендацією про навколишнє середовище)
  }

  @enduml
