@startuml

title Usecase for Lab7

left to right direction

actor Користувач
actor Споживач


rectangle Software {

  usecase (Авторизувати користувача)
  usecase (Отримати інформацію із рекамендацією про навколишнє середовище)

(Отримати інформацію із рекамендацією про навколишнє середовище) .> (Авторизувати користувача) : include

  :Користувач: -- (Авторизувати користувача)
  :Споживач: -- (Отримати інформацію із рекамендацією про навколишнє середовище)
  }

  @enduml
